### PR TITLE
Setup project and git

### PR DESCRIPTION
**Pull request by gnoriega27**
## What issue is this PR solving?
Closes: NA
## Description of change
Skeleton of the unity project and setup of basic git configurations for multiplatform development.

### CODE REVIEW

**Review by mjimenez98 — CHANGES_REQUESTED** [review]
I hate being petty about this but the professor specifically mentioned Unity version 2019.2.17 as shown below. This submission is on version 2019.2.21.

Screen Shot 2020-03-06 at 3 25 49 PM

**Comment by gnoriega27** [comment]
I knew this was somewhere but couldn't find it. Will fix right away

**Comment by gnoriega27** [comment]
@mjimenez98  Try again now!

**Review by mjimenez98 — APPROVED** [review]
Awesome! Thank you 😃

**Pull request merged**
