### PR TITLE
Aggressors 2

### LINKED ISSUE #10: Arrive for police officers
**Is your feature request related to a problem? Please describe.**
To attack the horde, police officers should arrive at the horde to shoot them.

**Describe the solution you would like**
Use arrive.

### LINKED ISSUE #12: Shooting for police officers
**Is your feature request related to a problem? Please describe.**
Police officers should be able to shoot at the horde to defeat it.

**Describe the solution you would like**
Use raycasts and detect collisions. Next issue after this will involve lowering the horde's health.

### PR DESCRIPTION
**Pull request by AnCapp**
## What issue is this PR solving?
Closes: https://github.com/StudioTBA/CoronaIO/issues/12
Closes: https://github.com/StudioTBA/CoronaIO/issues/10

## Description of change
Added a police officer agent that checks the surrounding area for targets.
If a target is found and withing range he will attack.
If the target moves closer he will retreat and attack at the same time.

### CODE REVIEW

**Comment by mjimenez98** [comment]
I am seeing this when I hit play. Is it correct?

9ba82622b023a72ffcd2260326b76d5a

Also, is there a demo for arrive behavior?

Finally, for the shooting, should I create another issue for bullet instantiation? I see the rays being fired in AttackingState.cs

**Comment by AnCapp** [comment]
There isn't a demo for the arrive behavior, but the same effect is produced in the attack and retreat state. For the bullets I guess you can make another issue for it but it also depends if we want to have a physical bullet or just an effect that goes off on the barrel of the gun and then just Ray cast to the target.

**Comment by mjimenez98** [comment]
Now I am getting compiler errors:

Screen Shot 2020-03-20 at 3 35 57 PM

Back to my original comment, would it be possible to have some sort of demo for arrive since we have to show it off as one of our AI behaviors? I would say it would be better to include with these changes but I can always add the demo to the backlog. Let me know what you think!

And regarding the shots, I personally would not be opposed to any solution as long as the player can notice the shots. Making the ray thicker, shot effect coming out of the gun, bullet prefab, whatever works. If you are okay with it, let's get this pull request through and then we'll come back to the bullets if we need to.

**Comment by AnCapp** [comment]
oh the errors are caused because the example name space doesn't exist anymore and i had to use it for the data holder I'll fix that, as for the arrive I'll make a separate state for it in a separate scene to show it off .

**Comment by AnCapp** [comment]
the change i made seems to be working try it out on your end

**Review by gnoriega27 — APPROVED** [review]
Nice. It works perfectly. I will merge it then.

**Comment by mjimenez98** [comment]
@AnCapp Good to see this has been merged!

I created another issue for the bullet.

Finally, regarding arrive and all the other AI behaviors, since they have to use the navmesh for pathfinding and our static environment has one, I will bring up tomorrow moving all the demos to scene _Sandbox_. That would include arrive for police officers so we'll revisit this tomorrow.

**Pull request merged**
